# when changing this file also consider `pyproject.toml` and `requirements.txt`
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: wizwtr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip

  # imported deps

  # Not on conda channels:
  - pip:
      - gracefulkiller~=0.4
      - mausy5043-common==1.10.1
      - python-homewizard-energy~=7.0
  - zeroconf=0.136

  # dev deps
  - jupyterlab
  - libtiff
#  - pandas-stubs
  - pipdeptree
  - pre-commit
  - scipy
