# when changing this file also consider `pyproject.toml` and `requirements.txt`
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: wizwtr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip

  # imported deps

  # Not on conda channels:
  - pip:
      - gracefulkiller~=0.4
      - mausy5043-common~=2.2
      # many breaking changes expected
      - python-homewizard-energy==8.3.0
  - matplotlib=3.10
  - pytz
  - sh=2.2
  - tabulate=0.9
  - zeroconf=0.146.1

  # dev deps
  - jupyterlab
  - libtiff
#  - pandas-stubs
  - pipdeptree
  - pre-commit
  - scipy
